// services/providers/telebirr.js
//
// Verifies a Telebirr transaction by fetching the official
// Telebirr public receipt page.
//
// No third-party verification API is used.
//
// IMPORTANT:
// - Telebirr receipt timestamps are treated as Ethiopia local time (UTC+3).
// - OCR reference mistakes are handled by generating carefully limited
//   candidate variants.
// - A candidate is ONLY accepted if the official Telebirr receipt endpoint
//   confirms it.
// - We never consider an OCR guess itself to be proof of payment.
//
// PERFORMANCE:
// - Original OCR reference is always checked first.
// - OCR candidates are ordered by likelihood.
// - Candidate requests are checked in small parallel batches.
// - As soon as one official receipt succeeds, the remaining requests
//   in the current batch are aborted.

const fetch = require("node-fetch");

const RECEIPT_BASE_URL =
  "https://transactioninfo.ethiotelecom.et/receipt/";

const REQUEST_TIMEOUT = 20000;

/*
 * Keep the number of OCR candidates bounded.
 *
 * A reference such as:
 *
 *   AB0S81
 *
 * could theoretically have several ambiguous characters.
 *
 * We generate combinations, but never an unlimited number
 * of requests.
 */
const MAX_REFERENCE_VARIANTS = 64;

/*
 * Number of OCR candidates checked concurrently after
 * the original OCR reference fails.
 *
 * 8 is a good balance:
 *
 * - Much faster than sequential requests.
 * - Doesn't unnecessarily hammer the official endpoint.
 * - Can be aborted when one candidate succeeds.
 */
const CANDIDATE_BATCH_SIZE = 8;

/*
 * OCR commonly confuses these characters.
 *
 * IMPORTANT:
 * We don't simply replace everything globally.
 *
 * Instead, generate candidates and let the official receipt
 * endpoint decide which candidate actually exists.
 */
const CONFUSABLE_GROUPS = [
  ["0", "O", "Q"],
  ["1", "I", "L"],
  ["2", "Z"],
  ["5", "S"],
  ["6", "G"],
  ["8", "B"],
];

/*
 * Create a lookup table so each character can be mapped
 * to its visually similar alternatives.
 */
const CONFUSABLE_LOOKUP = new Map();

for (const group of CONFUSABLE_GROUPS) {
  for (const char of group) {
    CONFUSABLE_LOOKUP.set(
      char,
      group
    );
  }
}

/**
 * Normalize an OCR/reference string.
 *
 * We intentionally keep this conservative.
 *
 * We:
 * - remove whitespace
 * - remove common separators
 * - convert to uppercase
 *
 * We DO NOT automatically convert O -> 0 or S -> 5 here.
 *
 * That would destroy legitimate references.
 */
function normalizeReference(value) {
  if (value == null) {
    return "";
  }

  return String(value)
    .trim()
    .toUpperCase()
    .replace(/[\s\-_.:]/g, "")
    .replace(/[^A-Z0-9]/g, "");
}

/**
 * Generate OCR-safe candidate references.
 *
 * The candidates are generated by edit distance.
 *
 * Order:
 *
 * 1. Original OCR reference.
 * 2. One-character correction.
 * 3. Two-character correction.
 * 4. Three-character correction.
 * 5. etc.
 *
 * This is significantly better than the old recursive DFS
 * because the old implementation could reach deeper combinations
 * before all simple OCR corrections had been tested.
 *
 * Example:
 *
 *   AB0S81
 *
 * starts approximately like:
 *
 *   AB0S81
 *   ABO S81
 *   AB0581
 *   AB0S8I
 *   AB0SB1
 *   AB0SBI
 *   ...
 */
function generateReferenceVariants(reference) {
  const normalized =
    normalizeReference(reference);

  if (!normalized) {
    return [];
  }

  const variants = [];
  const seen = new Set();

  function add(value) {
    if (
      !value ||
      seen.has(value) ||
      variants.length >=
        MAX_REFERENCE_VARIANTS
    ) {
      return;
    }

    seen.add(value);
    variants.push(value);
  }

  /*
   * Original OCR result is ALWAYS first.
   */
  add(normalized);

  /*
   * Generate candidates level-by-level.
   *
   * This makes one-character corrections appear before
   * two-character corrections.
   */
  let currentLevel = [
    normalized,
  ];

  while (
    currentLevel.length > 0 &&
    variants.length <
      MAX_REFERENCE_VARIANTS
  ) {
    const nextLevel = [];

    for (
      const current of
      currentLevel
    ) {
      for (
        let i = 0;
        i < current.length;
        i++
      ) {
        const char =
          current[i];

        const alternatives =
          CONFUSABLE_LOOKUP.get(
            char
          );

        if (!alternatives) {
          continue;
        }

        for (
          const alternative of
          alternatives
        ) {
          if (
            alternative ===
            char
          ) {
            continue;
          }

          const candidate =
            current.slice(0, i) +
            alternative +
            current.slice(i + 1);

          if (
            seen.has(candidate)
          ) {
            continue;
          }

          add(candidate);

          nextLevel.push(
            candidate
          );

          if (
            variants.length >=
            MAX_REFERENCE_VARIANTS
          ) {
            break;
          }
        }

        if (
          variants.length >=
          MAX_REFERENCE_VARIANTS
        ) {
          break;
        }
      }

      if (
        variants.length >=
        MAX_REFERENCE_VARIANTS
      ) {
        break;
      }
    }

    currentLevel =
      nextLevel;
  }

  return variants.slice(
    0,
    MAX_REFERENCE_VARIANTS
  );
}

/**
 * Strip HTML tags and decode common HTML entities.
 */
function cleanHtmlValue(value) {
  if (!value) {
    return null;
  }

  return String(value)
    .replace(
      /<br\s*\/?>/gi,
      " "
    )
    .replace(
      /&nbsp;/gi,
      " "
    )
    .replace(
      /&amp;/gi,
      "&"
    )
    .replace(
      /&quot;/gi,
      '"'
    )
    .replace(
      /&#39;/gi,
      "'"
    )
    .replace(
      /<[^>]*>/g,
      ""
    )
    .replace(
      /\s+/g,
      " "
    )
    .trim();
}

/**
 * Extract a value from a bilingual Telebirr receipt table.
 *
 * Example:
 *
 * <td>Invoice No</td>
 * <td>ABC123</td>
 */
function extractWithRegex(
  html,
  labelPattern
) {
  if (!html) {
    return null;
  }

  const escapedLabel =
    String(labelPattern).replace(
      /[.*+?^${}()|[\]\\]/g,
      "\\$&"
    );

  const patterns = [
    new RegExp(
      `${escapedLabel}` +
        `.*?<\\/td>` +
        `\\s*<td[^>]*>` +
        `\\s*([^<]+)`,
      "is"
    ),

    /*
     * Slightly more tolerant:
     * attributes / whitespace / nested markup.
     */
    new RegExp(
      `${escapedLabel}` +
        `.*?<td[^>]*>` +
        `\\s*(?:<[^>]+>\\s*)*` +
        `([^<]+)`,
      "is"
    ),
  ];

  for (
    const pattern of
    patterns
  ) {
    const match =
      html.match(pattern);

    if (!match) {
      continue;
    }

    const value =
      cleanHtmlValue(
        match[1]
      );

    if (value) {
      return value;
    }
  }

  return null;
}

/**
 * Extract settled amount.
 */
function extractSettledAmount(
  html
) {
  if (!html) {
    return null;
  }

  const patterns = [
    /*
     * Amharic + English.
     */
    /የተከፈለው\s*መጠን\s*\/?\s*Settled\s*Amount[\s\S]*?<td[^>]*>\s*([^<]+)/i,

    /*
     * English.
     */
    /Settled\s*Amount[\s\S]*?<td[^>]*>\s*([^<]+)/i,

    /*
     * More tolerant fallback.
     */
    /Settled\s*Amount[\s\S]{0,500}?([\d,]+(?:\.\d+)?\s*Birr)/i,

    /*
     * Birr amount near amount labels.
     */
    /(?:Amount|መጠን)[\s\S]{0,300}?([\d,]+(?:\.\d+)?\s*Birr)/i,
  ];

  for (
    const pattern of
    patterns
  ) {
    const match =
      html.match(pattern);

    if (!match) {
      continue;
    }

    const value =
      cleanHtmlValue(
        match[1]
      );

    if (
      value &&
      /\d/.test(value)
    ) {
      return value;
    }
  }

  return null;
}

/**
 * Extract the Telebirr receipt/invoice number.
 *
 * We prefer label-based extraction because arbitrary table
 * values can be things like "Completed".
 */
function extractReceiptNo(
  html
) {
  if (!html) {
    return null;
  }

  const labels = [
    "Invoice No",
    "Invoice Number",
    "Receipt No",
    "Receipt Number",
    "Transaction No",
    "Transaction Number",

    "Invoice No/Invoice Number",
    "Receipt No/Receipt Number",
  ];

  for (
    const label of
    labels
  ) {
    const value =
      extractWithRegex(
        html,
        label
      );

    if (!value) {
      continue;
    }

    const normalized =
      normalizeReference(
        value
      );

    /*
     * Receipt references are generally alphanumeric.
     *
     * Don't accept extremely short values.
     */
    if (
      normalized.length >= 6 &&
      normalized.length <= 100 &&
      /^[A-Z0-9]+$/.test(
        normalized
      )
    ) {
      return normalized;
    }
  }

  /*
   * Telebirr receipt-table fallback.
   */
  const tableMatch =
    html.match(
      /<td[^>]*class=["'][^"']*receipttableTd[^"']*receipttableTd2[^"']*["'][^>]*>\s*([^<]+)\s*<\/td>/i
    );

  if (tableMatch) {
    const normalized =
      normalizeReference(
        tableMatch[1]
      );

    if (
      normalized.length >= 6 &&
      /^[A-Z0-9]+$/.test(
        normalized
      )
    ) {
      return normalized;
    }
  }

  /*
   * Another fallback:
   *
   * Search specifically around "Invoice" or "Receipt"
   * rather than searching the entire HTML.
   */
  const contextualPatterns = [
    /Invoice[\s\S]{0,300}?([A-Z0-9]{6,100})/i,

    /Receipt[\s\S]{0,300}?([A-Z0-9]{6,100})/i,

    /Transaction\s*(?:No|Number|ID)[\s\S]{0,300}?([A-Z0-9]{6,100})/i,
  ];

  for (
    const pattern of
    contextualPatterns
  ) {
    const match =
      html.match(pattern);

    if (!match) {
      continue;
    }

    const normalized =
      normalizeReference(
        match[1]
      );

    if (
      normalized.length >= 6 &&
      /^[A-Z0-9]+$/.test(
        normalized
      )
    ) {
      return normalized;
    }
  }

  return null;
}

/**
 * Extract the actual Telebirr transaction timestamp.
 *
 * We prefer transaction/payment-specific fields.
 *
 * IMPORTANT:
 * Date-only values are rejected.
 */
function extractDate(html) {
  if (!html) {
    return null;
  }

  /*
   * Transaction-specific labels.
   */
  const labels = [
    "Transaction Date/Time",
    "Transaction Date / Time",
    "Transaction Date",
    "Transaction Time",

    "Payment Date/Time",
    "Payment Date / Time",
    "Payment Date",
    "Payment Time",

    "Date/Time",
    "Date / Time",

    "ቀን/ሰዓት",
    "ቀን / ሰዓት",
    "ቀን",
    "የክፍያ ቀን",
  ];

  for (
    const label of
    labels
  ) {
    const value =
      extractWithRegex(
        html,
        label
      );

    if (!value) {
      continue;
    }

    const parsed =
      parseTelebirrDate(
        value
      );

    if (parsed) {
      return parsed;
    }
  }

  /*
   * Search specifically inside table cells.
   *
   * This is safer than simply searching the entire HTML because
   * pages can contain unrelated dates in scripts, footer text,
   * metadata, etc.
   */
  const cellMatches =
    html.match(
      /<td[^>]*>[\s\S]*?<\/td>/gi
    ) || [];

  for (
    const cell of
    cellMatches
  ) {
    const text =
      cleanHtmlValue(
        cell
      );

    if (!text) {
      continue;
    }

    const parsed =
      parseTelebirrDate(
        text
      );

    if (parsed) {
      return parsed;
    }
  }

  /*
   * Final fallback.
   *
   * Only accept FULL date + time.
   */
  const patterns = [
    /\b\d{2}-\d{2}-\d{4}\s+\d{1,2}:\d{2}:\d{2}(?:\s*[AP]M)?\b/i,

    /\b\d{2}\/\d{2}\/\d{4}\s+\d{1,2}:\d{2}:\d{2}(?:\s*[AP]M)?\b/i,

    /\b\d{4}-\d{2}-\d{2}\s+\d{1,2}:\d{2}:\d{2}(?:\s*[AP]M)?\b/i,

    /\b\d{4}\/\d{2}\/\d{2}\s+\d{1,2}:\d{2}:\d{2}(?:\s*[AP]M)?\b/i,

    /*
     * Month-name formats.
     */
    /\b\d{1,2}\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+\d{4}\s+\d{1,2}:\d{2}:\d{2}(?:\s*[AP]M)?\b/i,

    /\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+\d{1,2},?\s+\d{4}\s+\d{1,2}:\d{2}:\d{2}(?:\s*[AP]M)?\b/i,
  ];

  for (
    const pattern of
    patterns
  ) {
    const match =
      html.match(pattern);

    if (!match) {
      continue;
    }

    const parsed =
      parseTelebirrDate(
        match[0]
      );

    if (parsed) {
      return parsed;
    }
  }

  return null;
}

/**
 * Parse supported Telebirr date formats.
 *
 * Every successful result is converted into UTC ISO.
 */
function parseTelebirrDate(
  value
) {
  if (!value) {
    return null;
  }

  let text =
    String(value)
      .replace(
        /\s+/g,
        " "
      )
      .trim();

  /*
   * Remove harmless punctuation around the value.
   */
  text =
    text.replace(
      /^[|:,-]+|[|:,-]+$/g,
      ""
    );

  /*
   * DD-MM-YYYY HH:mm:ss
   */
  let match =
    text.match(
      /^(\d{1,2})-(\d{1,2})-(\d{4})\s+(\d{1,2}):(\d{2}):(\d{2})$/
    );

  if (match) {
    const [
      ,
      day,
      month,
      year,
      hour,
      minute,
      second,
    ] = match;

    return buildIsoDate(
      year,
      month,
      day,
      hour,
      minute,
      second
    );
  }

  /*
   * DD-MM-YYYY HH:mm:ss AM/PM
   */
  match =
    text.match(
      /^(\d{1,2})-(\d{1,2})-(\d{4})\s+(\d{1,2}):(\d{2}):(\d{2})\s*(AM|PM)$/i
    );

  if (match) {
    const [
      ,
      day,
      month,
      year,
      hour,
      minute,
      second,
      meridiem,
    ] = match;

    return buildIsoDate(
      year,
      month,
      day,
      convert12HourTo24(
        hour,
        meridiem
      ),
      minute,
      second
    );
  }

  /*
   * DD/MM/YYYY HH:mm:ss
   */
  match =
    text.match(
      /^(\d{1,2})\/(\d{1,2})\/(\d{4})\s+(\d{1,2}):(\d{2}):(\d{2})$/
    );

  if (match) {
    const [
      ,
      day,
      month,
      year,
      hour,
      minute,
      second,
    ] = match;

    return buildIsoDate(
      year,
      month,
      day,
      hour,
      minute,
      second
    );
  }

  /*
   * DD/MM/YYYY HH:mm:ss AM/PM
   */
  match =
    text.match(
      /^(\d{1,2})\/(\d{1,2})\/(\d{4})\s+(\d{1,2}):(\d{2}):(\d{2})\s*(AM|PM)$/i
    );

  if (match) {
    const [
      ,
      day,
      month,
      year,
      hour,
      minute,
      second,
      meridiem,
    ] = match;

    return buildIsoDate(
      year,
      month,
      day,
      convert12HourTo24(
        hour,
        meridiem
      ),
      minute,
      second
    );
  }

  /*
   * YYYY-MM-DD HH:mm:ss
   */
  match =
    text.match(
      /^(\d{4})-(\d{1,2})-(\d{1,2})\s+(\d{1,2}):(\d{2}):(\d{2})$/
    );

  if (match) {
    const [
      ,
      year,
      month,
      day,
      hour,
      minute,
      second,
    ] = match;

    return buildIsoDate(
      year,
      month,
      day,
      hour,
      minute,
      second
    );
  }

  /*
   * YYYY-MM-DD HH:mm:ss AM/PM
   */
  match =
    text.match(
      /^(\d{4})-(\d{1,2})-(\d{1,2})\s+(\d{1,2}):(\d{2}):(\d{2})\s*(AM|PM)$/i
    );

  if (match) {
    const [
      ,
      year,
      month,
      day,
      hour,
      minute,
      second,
      meridiem,
    ] = match;

    return buildIsoDate(
      year,
      month,
      day,
      convert12HourTo24(
        hour,
        meridiem
      ),
      minute,
      second
    );
  }

  /*
   * YYYY/MM/DD HH:mm:ss
   */
  match =
    text.match(
      /^(\d{4})\/(\d{1,2})\/(\d{1,2})\s+(\d{1,2}):(\d{2}):(\d{2})$/
    );

  if (match) {
    const [
      ,
      year,
      month,
      day,
      hour,
      minute,
      second,
    ] = match;

    return buildIsoDate(
      year,
      month,
      day,
      hour,
      minute,
      second
    );
  }

  /*
   * YYYY/MM/DD HH:mm:ss AM/PM
   */
  match =
    text.match(
      /^(\d{4})\/(\d{1,2})\/(\d{1,2})\s+(\d{1,2}):(\d{2}):(\d{2})\s*(AM|PM)$/i
    );

  if (match) {
    const [
      ,
      year,
      month,
      day,
      hour,
      minute,
      second,
      meridiem,
    ] = match;

    return buildIsoDate(
      year,
      month,
      day,
      hour,
      minute,
      second
    );
  }

  /*
   * DD Mon YYYY HH:mm:ss
   *
   * Example:
   *
   * 08 Jun 2026 14:35:22
   */
  match =
    text.match(
      /^(\d{1,2})\s+([A-Za-z]+)\s+(\d{4})\s+(\d{1,2}):(\d{2}):(\d{2})(?:\s*(AM|PM))?$/i
    );

  if (match) {
    const [
      ,
      day,
      monthName,
      year,
      hour,
      minute,
      second,
      meridiem,
    ] = match;

    const month =
      monthNameToNumber(
        monthName
      );

    if (!month) {
      return null;
    }

    const finalHour =
      meridiem
        ? convert12HourTo24(
            hour,
            meridiem
          )
        : hour;

    if (
      finalHour == null
    ) {
      return null;
    }

    return buildIsoDate(
      year,
      month,
      day,
      finalHour,
      minute,
      second
    );
  }

  /*
   * Mon DD YYYY HH:mm:ss
   */
  match =
    text.match(
      /^([A-Za-z]+)\s+(\d{1,2}),?\s+(\d{4})\s+(\d{1,2}):(\d{2}):(\d{2})(?:\s*(AM|PM))?$/i
    );

  if (match) {
    const [
      ,
      monthName,
      day,
      year,
      hour,
      minute,
      second,
      meridiem,
    ] = match;

    const month =
      monthNameToNumber(
        monthName
      );

    if (!month) {
      return null;
    }

    const finalHour =
      meridiem
        ? convert12HourTo24(
            hour,
            meridiem
          )
        : hour;

    if (
      finalHour == null
    ) {
      return null;
    }

    return buildIsoDate(
      year,
      month,
      day,
      finalHour,
      minute,
      second
    );
  }

  return null;
}

/**
 * Convert month name to month number.
 */
function monthNameToNumber(
  value
) {
  const month =
    String(value)
      .trim()
      .toLowerCase()
      .slice(0, 3);

  const months = {
    jan: "01",
    feb: "02",
    mar: "03",
    apr: "04",
    may: "05",
    jun: "06",
    jul: "07",
    aug: "08",
    sep: "09",
    oct: "10",
    nov: "11",
    dec: "12",
  };

  return months[month] || null;
}

/**
 * Convert 12-hour time to 24-hour time.
 */
function convert12HourTo24(
  hour,
  meridiem
) {
  let h =
    Number(hour);

  if (
    !Number.isFinite(h) ||
    h < 1 ||
    h > 12
  ) {
    return null;
  }

  const upper =
    String(
      meridiem
    ).toUpperCase();

  if (
    upper === "AM"
  ) {
    if (h === 12) {
      h = 0;
    }
  } else if (
    upper === "PM"
  ) {
    if (h !== 12) {
      h += 12;
    }
  } else {
    return null;
  }

  return String(h)
    .padStart(2, "0");
}

/**
 * Build an ISO timestamp while explicitly treating the
 * input as Ethiopia local time (UTC+3).
 *
 * Example:
 *
 * Telebirr:
 *   13-08-2026 17:10:00
 *
 * Becomes:
 *   2026-08-13T14:10:00.000Z
 *
 * This is independent of the timezone of the server.
 */
function buildIsoDate(
  year,
  month,
  day,
  hour,
  minute,
  second
) {
  const y =
    Number(year);

  const m =
    Number(month);

  const d =
    Number(day);

  const h =
    Number(hour);

  const min =
    Number(minute);

  const s =
    Number(second);

  /*
   * Validate basic ranges before creating the date.
   */
  if (
    !Number.isInteger(y) ||
    !Number.isInteger(m) ||
    !Number.isInteger(d) ||
    !Number.isInteger(h) ||
    !Number.isInteger(min) ||
    !Number.isInteger(s)
  ) {
    return null;
  }

  if (
    m < 1 ||
    m > 12 ||
    d < 1 ||
    d > 31 ||
    h < 0 ||
    h > 23 ||
    min < 0 ||
    min > 59 ||
    s < 0 ||
    s > 59
  ) {
    return null;
  }

  /*
   * Telebirr time is Ethiopia local time.
   *
   * Ethiopia = UTC+03:00.
   *
   * Convert Ethiopian local time to UTC explicitly.
   */
  const utcMs =
    Date.UTC(
      y,
      m - 1,
      d,
      h,
      min,
      s
    ) -
    3 * 60 * 60 * 1000;

  const date =
    new Date(utcMs);

  if (
    Number.isNaN(
      date.getTime()
    )
  ) {
    return null;
  }

  /*
   * Make sure JavaScript didn't silently roll
   * an invalid date into another calendar date.
   */
  const expectedLocal = [
    y,
    m,
    d,
  ];

  const check =
    new Date(
      utcMs +
        3 * 60 * 60 * 1000
    );

  if (
    check.getUTCFullYear() !==
      expectedLocal[0] ||
    check.getUTCMonth() + 1 !==
      expectedLocal[1] ||
    check.getUTCDate() !==
      expectedLocal[2] ||
    check.getUTCHours() !==
      h ||
    check.getUTCMinutes() !==
      min ||
    check.getUTCSeconds() !==
      s
  ) {
    return null;
  }

  return date.toISOString();
}

/**
 * Convert HTML to plain text.
 *
 * Useful for debugging and fallback extraction.
 */
function htmlToText(html) {
  if (!html) {
    return "";
  }

  return String(html)
    .replace(
      /<script[\s\S]*?<\/script>/gi,
      " "
    )
    .replace(
      /<style[\s\S]*?<\/style>/gi,
      " "
    )
    .replace(
      /<br\s*\/?>/gi,
      "\n"
    )
    .replace(
      /<\/td>/gi,
      "\n"
    )
    .replace(
      /<\/tr>/gi,
      "\n"
    )
    .replace(
      /<[^>]*>/g,
      " "
    )
    .replace(
      /&nbsp;/gi,
      " "
    )
    .replace(
      /&amp;/gi,
      "&"
    )
    .replace(
      /\s+/g,
      " "
    )
    .trim();
}

/**
 * Parse the complete Telebirr receipt.
 */
function parseTelebirrHtml(
  html
) {
  if (
    !html ||
    typeof html !== "string"
  ) {
    return {
      success: false,

      error:
        "Empty Telebirr receipt response.",
    };
  }

  const receiptNo =
    extractReceiptNo(
      html
    );

  const payerName =
    extractWithRegex(
      html,
      "የከፋይ ስም/Payer Name"
    ) ||
    extractWithRegex(
      html,
      "Payer Name"
    );

  const transactionStatus =
    extractWithRegex(
      html,
      "የክፍያው ሁኔታ/transaction status"
    ) ||
    extractWithRegex(
      html,
      "Transaction Status"
    ) ||
    extractWithRegex(
      html,
      "Payment Status"
    );

  const creditedPartyName =
    extractWithRegex(
      html,
      "የገንዘብ ተቀባይ ስም/Credited Party name"
    ) ||
    extractWithRegex(
      html,
      "Credited Party name"
    ) ||
    extractWithRegex(
      html,
      "Credited Party Name"
    );

  const settledAmountRaw =
    extractSettledAmount(
      html
    );

  const paymentDate =
    extractDate(
      html
    );

  const amount =
    settledAmountRaw
      ? Number(
          settledAmountRaw
            .replace(
              /[^\d.]/g,
              ""
            )
        )
      : null;

  /*
   * A receipt should contain the core identifying fields.
   *
   * We intentionally do not require the timestamp to call the
   * receipt valid because some Telebirr pages may change their
   * presentation.
   */
  const isValid =
    Boolean(
      receiptNo &&
        payerName &&
        transactionStatus
    );

  if (!isValid) {
    return {
      success: false,

      error:
        "Receipt not found or could not be processed.",
    };
  }

  return {
    success: true,

    reference:
      receiptNo,

    amount,

    payer_name:
      payerName,

    receiver_name:
      creditedPartyName,

    /*
     * All of these point to the same normalized UTC timestamp.
     */
    transaction_date:
      paymentDate,

    transactionTime:
      paymentDate,

    paidAt:
      paymentDate,

    transaction_status:
      transactionStatus,
  };
}

/**
 * Fetch a single official Telebirr receipt.
 *
 * externalSignal is optional.
 *
 * verifyTelebirr() uses it to abort candidate requests when
 * another candidate has already succeeded.
 */
async function fetchReceipt(
  reference,
  externalSignal = null
) {
  const normalized =
    normalizeReference(
      reference
    );

  if (!normalized) {
    return {
      httpOk: false,

      status: 400,

      body: {
        success: false,

        error:
          "Invalid transaction reference.",
      },
    };
  }

  const url =
    `${RECEIPT_BASE_URL}${encodeURIComponent(
      normalized
    )}`;

  console.log(
    `[telebirr] checking official receipt: ${normalized}`
  );

  const controller =
    new AbortController();

  let externalAbortHandler =
    null;

  /*
   * Connect the caller's abort signal to this request.
   */
  if (externalSignal) {
    if (
      externalSignal.aborted
    ) {
      controller.abort();
    } else {
      externalAbortHandler =
        () => {
          controller.abort();
        };

      externalSignal.addEventListener(
        "abort",
        externalAbortHandler,
        {
          once: true,
        }
      );
    }
  }

  const timeout =
    setTimeout(
      () => {
        controller.abort();
      },
      REQUEST_TIMEOUT
    );

  try {
    const res =
      await fetch(
        url,
        {
          method: "GET",

          headers: {
            "User-Agent":
              "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/149 Safari/537.36",

            Accept:
              "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",

            "Accept-Language":
              "en-US,en;q=0.9",
          },

          redirect:
            "follow",

          signal:
            controller.signal,
        }
      );

    if (!res.ok) {
      return {
        httpOk: false,

        status:
          res.status,

        body: {
          success: false,

          error:
            `HTTP ${res.status}`,
        },
      };
    }

    const html =
      await res.text();

    const body =
      parseTelebirrHtml(
        html
      );

    /*
     * Debugging information without dumping the
     * entire receipt into production logs.
     */
    if (
      body.success
    ) {
      console.log(
        `[telebirr] receipt confirmed: ${normalized}`
      );

      console.log(
        `[telebirr] transactionTime: ${
          body.transactionTime ||
          "not found"
        }`
      );
    } else {
      console.log(
        `[telebirr] receipt page returned but could not be parsed: ${normalized}`
      );
    }

    return {
      httpOk:
        body.success,

      status:
        body.success
          ? 200
          : 404,

      body,
    };
  } catch (error) {
    const isAbort =
      error?.name ===
      "AbortError";

    /*
     * Abort is normal when another candidate has already
     * produced a valid official receipt.
     */
    if (isAbort) {
      return {
        httpOk: false,

        status: 499,

        body: {
          success: false,

          aborted: true,

          error:
            "Request aborted.",
        },
      };
    }

    console.error(
      `[telebirr] request failed for ${normalized}:`,
      error?.message ||
        error
    );

    return {
      httpOk: false,

      status: 502,

      body: {
        success: false,

        error:
          "Unable to contact Telebirr receipt service.",

        detail:
          error?.message ||
          null,
      },
    };
  } finally {
    clearTimeout(
      timeout
    );

    if (
      externalSignal &&
      externalAbortHandler
    ) {
      externalSignal.removeEventListener(
        "abort",
        externalAbortHandler
      );
    }
  }
}

/**
 * Verify Telebirr transaction.
 *
 * OCR may produce:
 *
 *   O instead of 0
 *   0 instead of O
 *   S instead of 5
 *   5 instead of S
 *   B instead of 8
 *   8 instead of B
 *   I instead of 1
 *   1 instead of I
 *   Z instead of 2
 *   2 instead of Z
 *   G instead of 6
 *   6 instead of G
 *
 * Verification strategy:
 *
 * 1. Check the exact OCR reference first.
 *
 * 2. If that fails, generate OCR variants.
 *
 * 3. Variants are ordered from most likely to least likely.
 *
 * 4. Check up to CANDIDATE_BATCH_SIZE variants concurrently.
 *
 * 5. When one official receipt succeeds, abort the rest
 *    of the current batch immediately.
 *
 * 6. Return the official receipt details.
 */
async function verifyTelebirr(
  reference
) {
  const normalized =
    normalizeReference(
      reference
    );

  if (!normalized) {
    return {
      httpOk: false,

      status: 400,

      body: {
        success: false,

        error:
          "Transaction reference is required.",
      },
    };
  }

  const variants =
    generateReferenceVariants(
      normalized
    );

  console.log(
    `[telebirr] OCR reference: ${normalized}`
  );

  console.log(
    `[telebirr] generated ${variants.length} candidate reference(s)`
  );

  /*
   * ---------------------------------------------------------
   * STEP 1
   * ---------------------------------------------------------
   *
   * Check the exact OCR result first.
   *
   * This is by far the most important optimization.
   *
   * If OCR is correct, only ONE HTTP request is made.
   */
  console.log(
    `[telebirr] checking original OCR reference first`
  );

  const originalAttempt =
    await fetchReceipt(
      normalized
    );

  if (
    originalAttempt.body?.success
  ) {
    console.log(
      `[telebirr] ORIGINAL reference confirmed: ${normalized}`
    );

    return {
      ...originalAttempt,

      body: {
        ...originalAttempt.body,

        /*
         * Official Telebirr reference is authoritative.
         */
        reference:
          originalAttempt.body.reference ||
          normalized,

        /*
         * Keep original OCR result for auditing.
         */
        ocr_reference:
          normalized,

        /*
         * This is the reference that actually worked.
         */
        matched_reference:
          normalized,

        /*
         * OCR was already correct.
         */
        ocr_corrected:
          false,
      },
    };
  }

  /*
   * ---------------------------------------------------------
   * STEP 2
   * ---------------------------------------------------------
   *
   * Original OCR reference failed.
   *
   * Now check the most likely OCR corrections.
   */
  const remaining =
    variants.slice(1);

  if (
    remaining.length === 0
  ) {
    console.log(
      `[telebirr] no OCR variants available`
    );

    return {
      ...originalAttempt,

      body: {
        ...(originalAttempt.body || {
          success: false,
        }),

        ocr_reference:
          normalized,

        ocr_corrected:
          false,
      },
    };
  }

  let firstFailure =
    originalAttempt;

  /*
   * ---------------------------------------------------------
   * STEP 3
   * ---------------------------------------------------------
   *
   * Process candidates in small parallel batches.
   */
  for (
    let start = 0;
    start < remaining.length;
    start += CANDIDATE_BATCH_SIZE
  ) {
    const batch =
      remaining.slice(
        start,
        start +
          CANDIDATE_BATCH_SIZE
      );

    const batchEnd =
      Math.min(
        start +
          CANDIDATE_BATCH_SIZE,
        remaining.length
      );

    console.log(
      `[telebirr] checking candidate batch ${start + 1}-${batchEnd} of ${remaining.length}`
    );

    /*
     * One AbortController controls this entire batch.
     *
     * If one candidate succeeds, all remaining in-flight
     * requests in this batch receive the abort signal.
     */
    const batchController =
      new AbortController();

    /*
     * Keep the winner in a shared variable.
     *
     * JavaScript runs these callbacks on the event loop,
     * so only the first successful result should set it.
     */
    let winner =
      null;

    const promises =
      batch.map(
        async (
          candidate,
          batchIndex
        ) => {
          console.log(
            `[telebirr] trying candidate ${
              start +
              batchIndex +
              2
            }/${variants.length}: ${candidate}`
          );

          const result =
            await fetchReceipt(
              candidate,
              batchController.signal
            );

          /*
           * Only a successfully parsed official receipt
           * can become the winner.
           */
          if (
            result.body?.success &&
            !winner
          ) {
            winner = {
              candidate,
              result,
            };

            console.log(
              `[telebirr] candidate succeeded: ${candidate}`
            );

            /*
             * Abort the remaining requests in this batch.
             */
            batchController.abort();
          }

          return {
            candidate,
            result,
          };
        }
      );

    const results =
      await Promise.all(
        promises
      );

    /*
     * -------------------------------------------------------
     * SUCCESS
     * -------------------------------------------------------
     *
     * If any candidate found an official receipt, return it
     * immediately.
     */
    if (winner) {
      const {
        candidate,
        result,
      } = winner;

      console.log(
        `[telebirr] SUCCESS using candidate: ${candidate}`
      );

      console.log(
        `[telebirr] official reference: ${
          result.body.reference ||
          candidate
        }`
      );

      console.log(
        `[telebirr] amount: ${
          result.body.amount ??
          "not found"
        }`
      );

      console.log(
        `[telebirr] payer: ${
          result.body.payer_name ||
          "not found"
        }`
      );

      console.log(
        `[telebirr] receiver: ${
          result.body.receiver_name ||
          "not found"
        }`
      );

      console.log(
        `[telebirr] transaction time: ${
          result.body.transactionTime ||
          "not found"
        }`
      );

      console.log(
        `[telebirr] status: ${
          result.body.transaction_status ||
          "not found"
        }`
      );

      return {
        ...result,

        body: {
          ...result.body,

          /*
           * The official receipt is authoritative.
           */
          reference:
            result.body.reference ||
            candidate,

          /*
           * Original OCR reference.
           */
          ocr_reference:
            normalized,

          /*
           * Candidate that actually matched
           * the official Telebirr page.
           */
          matched_reference:
            candidate,

          /*
           * Whether OCR required correction.
           */
          ocr_corrected:
            candidate !==
            normalized,
        },
      };
    }

    /*
     * -------------------------------------------------------
     * NO SUCCESS IN THIS BATCH
     * -------------------------------------------------------
     *
     * Keep a useful failure response.
     *
     * Aborted requests are intentionally ignored because
     * an abort does not mean the candidate was invalid.
     */
    for (
      const item of
      results
    ) {
      if (
        !item.result.body?.aborted &&
        !firstFailure
      ) {
        firstFailure =
          item.result;
      }
    }

    /*
     * Move to the next batch.
     *
     * There is deliberately no artificial delay here.
     */
  }

  /*
   * ---------------------------------------------------------
   * COMPLETE FAILURE
   * ---------------------------------------------------------
   */
  console.log(
    `[telebirr] no official receipt matched OCR reference or generated candidates`
  );

  return {
    ...(firstFailure || {
      httpOk: false,

      status: 404,

      body: {
        success: false,

        error:
          "Telebirr transaction could not be found.",
      },
    }),

    body: {
      ...(firstFailure?.body || {
        success: false,

        error:
          "Telebirr transaction could not be found.",
      }),

      /*
       * Preserve the original OCR value for audit/debugging.
       */
      ocr_reference:
        normalized,

      ocr_corrected:
        false,
    },
  };
}

module.exports = {
  verifyTelebirr,
};