const mongoose = require("mongoose");

// Generates the suffix automatically from the account number.
//
// CBE       -> last 8 digits
// Abyssinia -> last 5 digits
// Other     -> empty string
function generateAccountSuffix(provider, accountNumber) {
  const digits = String(accountNumber || "").replace(/\D/g, "");
  const normalizedProvider = String(provider || "").trim().toLowerCase();

  if (normalizedProvider === "cbe") {
    return digits.slice(-8);
  }

  if (normalizedProvider === "abyssinia") {
    return digits.slice(-5);
  }

  return "";
}

// Which provider/receiving account this business accepts payments on.
//
// Admin/owner-managed (section 8-10 of the billing upgrade spec).
// The verify flow reads these instead of the old
// User.cbeAccountSuffix / User.abyssiniaAccountSuffix fields.
//
// The waiter never supplies accountSuffix.
// The backend generates it automatically from accountNumber.
//
// CBE       -> last 8 digits
// Abyssinia -> last 5 digits
// Other     -> no suffix
const paymentAccountSchema = new mongoose.Schema(
  {
    businessId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    provider: {
      type: String,
      enum: [
        "CBE",
        "Telebirr",
        "Dashen",
        "Abyssinia",
        "CBEBirr",
        "MPesa",
        "Awash",
      ],
      required: true,
    },

    // Account/wallet number as shown to customers.
    accountNumber: {
      type: String,
      required: true,
      trim: true,
    },

    // Used to match OCR-extracted receiver name.
    accountHolderName: {
      type: String,
      required: true,
      trim: true,
    },

    // Automatically generated by the backend.
    //
    // CBE       -> last 8 digits of accountNumber
    // Abyssinia -> last 5 digits of accountNumber
    //
    // Never requested from the waiter/frontend.
    accountSuffix: {
      type: String,
      default: "",
    },

    enabled: {
      type: Boolean,
      default: true,
    },

    createdAt: {
      type: Date,
      default: Date.now,
    },

    updatedAt: {
      type: Date,
      default: Date.now,
    },
  },
  {
    // Automatically maintains updatedAt when using save/update methods
    timestamps: true,
  }
);

// Automatically generate the suffix before saving.
//
// This covers both:
// - Creating a new payment account
// - Editing an existing account number
paymentAccountSchema.pre("save", function (next) {
  this.accountSuffix = generateAccountSuffix(
    this.provider,
    this.accountNumber
  );

  next();
});

// A business should only have one configured account per provider.
// This avoids ambiguity about which account to match a receipt against.
paymentAccountSchema.index(
  { businessId: 1, provider: 1 },
  { unique: true }
);

module.exports = mongoose.model("PaymentAccount", paymentAccountSchema);